---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: nginx-multi-target-pipeline
description: Nginx Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: prod-us
  - targetId: prod-eu

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod
description: Production Environment
multiTarget:
  targetIds: [prod-us, prod-eu]

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod-us
description: US Production Environment
gke:
  cluster: projects/yougo-k8-hardway-256417/locations/us-central1-c/clusters/us-prod

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: prod-eu
description: EU Environment
requireApproval: true
gke:
  cluster: projects/yougo-k8-hardway-256417/locations/europe-central2-a/clusters/eu-prod
