---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: nginx-multi-target-pipeline
description: Nginx Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: us-prod
  - targetId: eu-prod

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: regional-prod
description: Production Environment
multiTarget:
  targetIds: [us-prod, eu-prod]

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: us-prod
description: US Production Environment
gke:
  cluster: projects/yougo-dev-369515/locations/us-central1-c/clusters/us-prod

---
apiVersion: deploy.cloud.google.com/v1beta1
kind: Target
metadata:
  name: eu-prod
description: EU Environment
requireApproval: true
gke:
  cluster: projects/yougo-dev-369515/locations/europe-central2-a/clusters/eu-prod
